Create table PRODUCT_MEDDRA_HIERARCHY (
ATC_LVL_1 varchar(200) NOT NULL,
ATC_LVL_1_DESC            varchar(1000) NOT NULL,
ATC_LVL_2 varchar(200) NOT NULL,
ATC_LVL_2_DESC            varchar(1000) NOT NULL,
ATC_LVL_3 varchar(200) NOT NULL,
ATC_LVL_3_DESC            varchar(1000) NOT NULL,
ATC_LVL_4 varchar(200) NOT NULL,
ATC_LVL_4_DESC            varchar(1000) NOT NULL,
ATC_LVL_5 varchar(200) NOT NULL,
ATC_LVL_5_DESC            varchar(1000) NOT NULL,
RXNORM            varchar(200) NOT NULL,
RXNORM_DESC varchar(1000) NOT NULL);